configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Y2Q0NWRiMGEwMmJmZTg1ZTY3ZWViOTg5YWY1MjkwZjM1YmJjZDJjZGFkYjZmYTlmODFjN2I0ZTMwZDBlYjhlMDkyMjRmZjg4ZjI4YjY4YTE5MWJkZGY2MjVmM2VlY2M4ZGQxZGU5YmRiZDY1YmQwOGI0MmUxODU4NWRkYjkyMDc=
